// Common action types (suffixes)
export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT',
} as const

// Authentication action types
export const AUTH_ACTION_TYPES = {
  LOGIN: 'AUTH_LOGIN',
  REGISTER: 'AUTH_REGISTER',
  LOGOUT: 'AUTH_LOGOUT',
  FETCH_PROFILE: 'AUTH_FETCH_PROFILE',
  UPDATE_PROFILE: 'AUTH_UPDATE_PROFILE',
  CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
} as const

// Category action types
export const CATEGORY_ACTION_TYPES = {
  FETCH_CATEGORIES: 'CATEGORY_FETCH_CATEGORIES',
  FETCH_CATEGORY: 'CATEGORY_FETCH_CATEGORY',
  CREATE_CATEGORY: 'CATEGORY_CREATE_CATEGORY',
  UPDATE_CATEGORY: 'CATEGORY_UPDATE_CATEGORY',
  DELETE_CATEGORY: 'CATEGORY_DELETE_CATEGORY',
  CLEAR_CURRENT_CATEGORY: 'CATEGORY_CLEAR_CURRENT_CATEGORY',
  CLEAR_ERROR: 'CATEGORY_CLEAR_ERROR',
} as const

// Transaction action types
export const TRANSACTION_ACTION_TYPES = {
  FETCH_TRANSACTIONS: 'TRANSACTION_FETCH_TRANSACTIONS',
  FETCH_TRANSACTION: 'TRANSACTION_FETCH_TRANSACTION',
  CREATE_TRANSACTION: 'TRANSACTION_CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'TRANSACTION_UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'TRANSACTION_DELETE_TRANSACTION',
  CLEAR_CURRENT_TRANSACTION: 'TRANSACTION_CLEAR_CURRENT_TRANSACTION',
  CLEAR_ERROR: 'TRANSACTION_CLEAR_ERROR',
} as const

// Budget action types
export const BUDGET_ACTION_TYPES = {
  FETCH_BUDGETS: 'BUDGET_FETCH_BUDGETS',
  FETCH_BUDGET: 'BUDGET_FETCH_BUDGET',
  CREATE_BUDGET: 'BUDGET_CREATE_BUDGET',
  UPDATE_BUDGET: 'BUDGET_UPDATE_BUDGET',
  DELETE_BUDGET: 'BUDGET_DELETE_BUDGET',
  FETCH_BUDGET_PROGRESS: 'BUDGET_FETCH_BUDGET_PROGRESS',
  FETCH_ALL_BUDGET_PROGRESS: 'BUDGET_FETCH_ALL_BUDGET_PROGRESS',
  CLEAR_CURRENT_BUDGET: 'BUDGET_CLEAR_CURRENT_BUDGET',
  CLEAR_ERROR: 'BUDGET_CLEAR_ERROR',
} as const

// Dashboard action types
export const DASHBOARD_ACTION_TYPES = {
  FETCH_SUMMARY: 'DASHBOARD_FETCH_SUMMARY',
  FETCH_RECENT_TRANSACTIONS: 'DASHBOARD_FETCH_RECENT_TRANSACTIONS',
  FETCH_CATEGORY_BREAKDOWN: 'DASHBOARD_FETCH_CATEGORY_BREAKDOWN',
  FETCH_MONTHLY_TRENDS: 'DASHBOARD_FETCH_MONTHLY_TRENDS',
  CLEAR_ERROR: 'DASHBOARD_CLEAR_ERROR',
} as const

// Export/Report action types
export const EXPORT_ACTION_TYPES = {
  EXPORT_CSV: 'EXPORT_CSV',
  EXPORT_JSON: 'EXPORT_JSON',
  EXPORT_BUDGET_CSV: 'EXPORT_BUDGET_CSV',
  EXPORT_BUDGET_JSON: 'EXPORT_BUDGET_JSON',
} as const
